- content/playground.html
When the playground is loaded in production over HTTP, Swagger's UI code fails to fetch the definitions of the models because they are referenced using HTTPS. This works locally because the connection is not encrypted but in production, unless the playground page is loaded over HTTPS to begin with, this will fail.
This change is a horrible hack to redirect the user to the secure playground page when we detect they they are on the production site and that they have loaded the page using HTTP rather than HTTPS
> Redirect insecure connections to the playground

- specs/java/smoke/tests/src/test/java/com/strava/api/v3/services/ApiTest.java
- specs/java/smoke/tests/src/test/java/com/strava/api/v3/services/AthletesApiTest.java
- specs/java/smoke/tests/src/test/java/com/strava/api/v3/services/StreamsApiTest.java
- swagger/stream.json.mustache
- swagger/swagger.json.mustache
This change defines the streams models and endpoints available through the API, for activities, segments and segment efforts.
Addresses https://github.com/strava/developers.strava.com/issues/15
> Adds streams endpoints and models

- swagger/athlete.json.mustache
- swagger/club.json.mustache
- swagger/gear.json.mustache
Background:
This is the developers.strava.com counterpart to [CP-1719](https://strava.atlassian.net/browse/CP-1719). Developers were getting confused about the possible values and meaning of the `resource_state` attribute, so we want to be more explicit about what it means.
Solution:
Update the API documentation to reflect the possible values for resource_state.
Result:
developers.strava.com has updated `resource_state` documentation.
Completes [CP-1731](https://strava.atlassian.net/browse/CP-1731)
> [CP-1731] Revise definition of `resource_state` on API docs

- swagger/swagger.json.mustache
I noticed that the age and weight bands in the live Strava site have been updated and are different from the ones in the API docs. These changes update the docs to reflect reality.
> Update age and weight bands in documentation

- README.md
- scripts/deploy_local_changes_p1324.sh
I've been taking some notes as I went through my first pull request on developers.strava.com, and I just want to update the documentation to reflect some chokepoints and discrepancies.
Completes [CP-1734](https://strava.atlassian.net/browse/CP-1734)
> [CP-1734] Clean up developers.strava.com documentation

- Dockerfile
- specs/java/compile.sh
- specs/java/generate.sh
- specs/java/smoke/tests/src/test/java/com/strava/api/v3/services/StreamsApiTest.java
- specs/java/test.sh
- swagger/activity.json.mustache
- swagger/comment.json.mustache
- swagger/photo.json.mustache
- swagger/segment.json.mustache
- swagger/segment_leaderboard.json.mustache
- swagger/swagger.json.mustache
- swagger/upload.json.mustache
This change updates the type of several identifiers to be int64: activites, segments, uploads in particular.
Along with this, it makes some updates to the test harness and the generation of the documentation and test code:
- we have been using `io.swagger.codegen.Codegen` as a main class to generate both the documentation and the test Java code. As it turns out, this class doesn't fail loudly and invoking it directly will not print an error message and not return an error code. Instead, we should call `io.swagger.codegen.SwaggerCodegen`, which is the main class invoked by the Swagger CLI.
- when the Docker image is built after having run the tests locally, it main contain the generated Java code at `specs/java/generated`. This is because we `COPY` the entire source tree and that the tree …
> [CP-1710] Switches several identifiers to int64

- CONTRIBUTING.md
- content/docs/changelog.md
- layouts/index.html
First pass at a changelog.
Background:
There is currently no changelog in [developers.strava.com](https://developers.strava.com). However, changelogs are important because they offer a permanent, external record of functional changes to a public service.
Solution:
Add a changelog. A link to the old changelog was already linked on the [developers.strava.com](https://developers.strava.com) homepage, so all that was needed was to create a new markdown file and update the link to be a local reference.
I wanted to make it simple for developers to add changelog entries while ensuring that the content was presented logically and easily readable, so I relied heavily on built-in Markdown conventions and looked around at other well-documented external APIs for stylistic inspiration; the current …
> [CP-1770] Add a changelog

- content/docs/rate-limiting.md
- layouts/index.html
- layouts/partials/header.html
Background:
Rate limiting is an important aspect of most public APIs. [developers.strava.com](https://developers.strava.com) needs a page that explains our rate limiting policies.
Solution:
Add a page with the Strava API rate limiting information. Add a card-block on the home page, as well as a link to the new page in the header dropdown bar.
Result:
[developers.strava.com](https://developers.strava.com) has a page about rate limits.
Completes [CP-1772](https://strava.atlassian.net/browse/CP-1772)
**Rate limit page**
**Home page**
Before:
After:
**Dropdown bar**
Before:
After:
> [CP-1772] Add rate limits page

- README.md
- scripts/deploy_local_changes.sh
Disclaimer: I don't have much experience writing bash scripts; please have mercy 😨 . This script has just helped me personally so I thought it would help others as well.
Background:
The developers.strava.com documentation development cycle is currently pretty slow. It would be nice if there was a script to automate things
Solution:
Write a script to compile models and documentation, and deploy the website locally.\
Result:
Tighter feedback and faster development.
Completes [CP-1741](https://strava.atlassian.net/browse/CP-1741)
> [CP-1741] Bash script to speed up local development

- layouts/index.html
Input welcome for homepage styling and the box order.
Background:
There is a little box on [developers.strava.com](https://developers.strava.com) which says that Libraries are "Coming soon." Unfortunately this is not the case, since packaging these libraries appropriately and keeping track of various versions is not something the Strava API Team has the bandwith to do.
Solution:
Remove the Client Libraries box from the homepage.
Result:
People won't expect Client Libraries that we're not generating.
Completes [CP-1790](https://strava.atlassian.net/browse/CP-1790)
> [CP-1790] Remove Client Libraries from homepage

- .gitignore
- specs/java/smoke/tests/src/test/java/com/strava/api/v3/services/AthletesApiTest.java
- swagger/swagger.json.mustache
Removes:
* `activities/following`
* `activities/:id/related`
* `athletes/:id/following`
* `athletes/:id/friends`
* `athletes/:id/both-following`
Specifies that these endpoints are only available to the authenticated athlete:
* `segment_efforts/:id`
* `segment_efforts/:id/streams`
* `segments/:id/all_efforts`
* `athletes/:id`
Completes [ET-4519](https://strava.atlassian.net/browse/ET-4519)
> [ET-4519] Remove OPD endpoints

- content/docs/webhooks.md
- layouts/index.html
The new webhooks page is pretty long, so I'd recommend pulling down the branch if you want to see the whole thing. I'm including a screenshot of the top of it for reference.
[developers.strava.com](https://developers.strava.com) home page:
Webhook events page:
> Add webhooks documentation

- codegen/src/main/resources/strava-html/reference.mustache
- swagger/swagger.json.mustache
I added sanitized responses for all clubs endpoints, removed the deprecated `clubs/id/announcements` endpoint from the swagger spec altogether, and fixed little english nits along the way. I also noticed a bug in the model that's being returned in the `clubs/id/leave` endpoint, which I documented in [API-708](https://strava.atlassian.net/browse/API-708).
There's a lot of content here but no new design elements, so I don't think a screenshot would be very useful. I think english errors and keeping the data safe / anonymous is what's most important.
cc @mindy-stivers 
Completes [API-700](https://strava.atlassian.net/browse/API-700)
> [API-700] Clean up clubs endpoints

- swagger/swagger.json.mustache
Fixing the typo in the Segment Leaderboard API.
> [API-711] Typo in getLeaderboardBySegmentId

- swagger/swagger.json.mustache
This is the last one.... Note that the detailed activity representations are identical for a couple of the endpoints -- I just copied them, so no need to re-review the detailed activity responses.
Adds sample responses and cleans up the documentation for each of the activities endpoints. I'm primarily looking for english typos and data sanitization in review.
Completes [API-698](https://strava.atlassian.net/browse/API-698)
> [API-698] Clean up activities endpoints and documentation

- swagger/swagger.json.mustache
This PR updates the sample response for the segments/{id}/leaderboard endpoint to reflect what's actually returned by the endpoint.
> Updated response for segments/{id}/leaderboard endpoint

- swagger/swagger.json.mustache
Added the Create Activity endpoint documentation for manual activities. Stubbed out all the identifying information (hopefully)
> [API-733] Manual Activity missing from developers.strava.com

- swagger/swagger.json.mustache
JIRA - https://strava.atlassian.net/browse/API-817
Two of the API users have notified us that the star/unstar API is broken
https://groups.google.com/forum/#!topic/strava-api/wXq2shpYWeU
Turns out, the API requires a `starred` field to star a segment. The absence of that parameter results to technically `unstarring` the segment. The API endpoint works fine but the cause of the confusion was the missing piece in the documentation. This PR fixes the documentation.
> API-817 Star/Unstar segment API (broken) documentation

- codegen/src/main/resources/strava-html/param.mustache
- swagger/activity.json.mustache
Let me explain with screenshots.
Before : 
After : 
Is this better? Also, please let me know if this is going to break any of the swagger built code. I dont think so but a confirmation would be great.
> Displaying better information

- content/docs/authentication.md
- content/docs/changelog.md
Jira - https://strava.atlassian.net/browse/API-865
As per https://strava.atlassian.net/browse/API-863, we now return the scope information for the `oauth/authorize` endpoint. These are the corresponding documentation changes.
Screenshot -
> [API-865] Documentation changes for returning scope information

- swagger/activity_stats.json.mustache
- swagger/activity_total.json.mustache
- swagger/swagger.json.mustache
These details went missing when we moved the api doc to swagger. Adding
them back based on the old doc.
First doc update! 🎉 I'd say we don't need to add this to changelog? Endpoint is not changing, just clarifying the doc.
cc: @MateoAO
> [Needful] Clarify fields and parameters for get athlete stats endpoint

- content/docs/index.md
I intended just to fix the formatting of this section
but one thing led to another, see notes lines.
> Fixed formatting of examples and removed JSON-P section

- swagger/activity.json.mustache
These fields are already returned in the API, but not documented in this
new doc, porting them over from the old doc.
While I'm in the zone writing api doc, here is another one for you all. Debating if I should add this to the changelog... it's not new for the api, but was never documented in the swagger version of the api doc 🤷‍♀️
> [API-861] Add power related fields to summary and detailed activity

- content/docs/partner-uploads.md
Megha requested these docs to help convince partners to send more custom data. The bigger piece are mockups, which aren't in our court. 
Anyhow, hidden in this PR is one question to ponder (see notes)
> [API-922] Add ATD Score to partner upload docs
